name: Check code quality
on:
  pull_request:
    branches: [ backend ]
jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - name: Get code onto system
        uses: actions/checkout@v3
      - name: Setup node v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: Setup env file
        env:
          ENV_FILE: ${{ secrets.ENV_BACKEND }}
        run: echo "$ENV_FILE" > .env
      - run: yarn ci
      - run: yarn tsc --noEmit
      - run: yarn lint:ci
